export const AUTHENTICATE = 'AUTHENTICATE';
export type AUTHENTICATE = typeof AUTHENTICATE;
export const UNAUTHENTICATE = 'UNAUTHENTICATE';
export type UNAUTHENTICATE = typeof UNAUTHENTICATE;
export const GET_BANK_ACCOUNTS = 'GET_BANK_ACCOUNTS';
export type GET_BANK_ACCOUNTS = typeof GET_BANK_ACCOUNTS;
